language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIIFNOKDUD
  secret_access_key:
    secure: Gq3nDGBmz2n63QDdKlJAwpvwkXY1VlAAzVOjPRAWOGr1HWyGHEhwWJ6FCO3Cgd1dHfOBroc+L2t0MVkNBKo51mVBxl64SynLpjuujT1vPd9JoX2q15Lcm9PKiJLhiIjVkQuNuno+YjNj1uZmEnPLs+UvkBPee+8fIJ39Z2tggB31GAVAILSpFxyp/MQ9vs0NJBs3BVlPQY+KvRbeVJG5pisrltfvvRTCDuCwJy0XLh52PugtjJexk9DRzt5kC7wsp65oVs0XvKMZI9zKdWLRPP2ok3TDsHxb8TTdIRDvvw5EUlcCEhBH9tbjFJC8D6zU0L2PP3sq2CV2JLgLWMYLM7SnN4IWOLIDW1YXVAkalGVxDH9XfvmbqwOSo6enTML9uqz4PzCNFlXftie/2pU0PO/2n7tYP/IbjSfzxqXTS73XZ7Sf+/r14NiRqeniUidbAMxGOHdixJUL1wDGJE23+x1BFQO8vzk/Qg0a2N18x/LKFIEGovXzFos2+9ukZltJHfZSguWkbIw+pNEE6lkQwn7T9K7byKx+cAbkIVTu/QI+Q7ZmzL/w3VQCilor/P9yGrrXFUoD+G+erroHXdSyiM2UUN9FEl3ajvEPqsvNM/av8c7BQG6qwaSxxXRhWLywBoO/gRDny4Pkpq2XSusauguYd4cFhmdFnkM1r/MMFl0=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: jcoin_datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/JCOIN_datadictionary
    all_branches: true
