$schema: "http://json-schema.org/draft-04/schema#"

id: "environment"
title: Environment
type: object
namespace: http://gdc.nci.nih.gov
category: administrative
program: '*'
project: '*'
description: >
  The collection of all data related to a specific participant in the
  context of a specific project.
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - project_id
  - created_datetime
  - updated_datetime
  - state

links:
  - name: protocols
    backref: Environments
    label: recruited_at
    target_type: protocol
    multiplicity: many_to_one
    required: true

required:
  - submitter_id
  - type
  - protocols

uniqueKeys:
  - [id]
  - [project_id, submitter_id]

# Protocol properties
properties:
  
  $ref: "_definitions.yaml#/ubiquitous_properties"

  order_detailed:
    description: >
      tbd
    type: integer

  product_id:
    description: >
      tbd
    type: integer 

  other_id:  
    description: >
      tbd
    type: integer

  product_quantity:  
    description: >
      tbd
    type: integer

  protocols:
    $ref: "_definitions.yaml#/to_one"
  project_id:
    $ref: "_definitions.yaml#/project_id"
  created_datetime:
    $ref: "_definitions.yaml#/datetime"
  updated_datetime:
    $ref: "_definitions.yaml#/datetime"