$schema: "http://json-schema.org/draft-04/schema#"

id: "environment"
title: Environment
type: object
namespace: https://jcoin.datacommons.io/dd
category: administrative
program: '*'
project: '*'
description: >
  The collection of all data related to a specific environment in the
  context of a specific project.
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - project_id
  - created_datetime
  - updated_datetime
  - state

links:
  - name: centers
    backref: Environments
    label: recruited_at
    target_type: center
    multiplicity: many_to_one
    required: true

required:
  - submitter_id
  - type
  - centers

uniqueKeys:
  - [id]
  - [project_id, submitter_id]

# Protocol properties
properties:
  
  $ref: "_definitions.yaml#/ubiquitous_properties"

  order_detailed:
    description: >
      tbd
    type: integer

  product_id:
    description: >
      tbd
    type: integer 

  other_id:  
    description: >
      tbd
    type: integer

  product_quantity:  
    description: >
      tbd
    type: integer

  percent_of_county_residents_less_than_18_below_FPL_using_census_data:
    description: >
      tbd
    type:
      - string

  percent_of_population_designated_as_urban_using_census_data:
    description: >
      tbd
    type:
      - string

  county_licensed_MAT_providers_using_admin_data:
    description: >
      tbd
    type:
      - string 
  
  centers_of_treatment_innovation_using_admin_data:
    description: >
      tbd
    type:
      - string

  recovery_advocates_using_admin_data:
    description: >
      tbd
    type:
      - string

  county_overdose_rates_using_admin_data:
    description: >
      tbd
    type: number
  
  county_ER_visits_using_admin_data:
    description: >
      tbd
    type: integer

  centers:
    $ref: "_definitions.yaml#/to_one"
  
